# Generated by Django 5.2.7 on 2025-11-07 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('kelas', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
