# Generated by Django 5.2.7 on 2025-11-14 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_profile_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='kelas',
        ),
        migrations.AddField(
            model_name='profile',
            name='foto',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
