# Generated by Django 5.2.7 on 2025-11-14 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_profile_kelas_profile_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='kelas',
            field=models.CharField(default='7A', max_length=5),
        ),
        migrations.AlterField(
            model_name='profile',
            name='foto',
            field=models.ImageField(default='profile_pics/default.jpg', upload_to='profile_pics'),
        ),
    ]
