# Generated by Django 5.2.7 on 2025-11-19 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_profile_foto'),
        ('main', '0004_profile_kelas_alter_profile_foto'),
    ]

    operations = [
    ]
