# Generated by Django 5.2.7 on 2025-11-27 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_merge_20251119_2316'),
        ('main', '0008_riwayatsimulasi'),
    ]

    operations = [
    ]
