# Generated by Django 5.2.7 on 2025-12-18 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_merge_0005_merge_20251119_2316_0008_riwayatsimulasi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Materi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('urutan', models.IntegerField(help_text='Urutan materi (1, 2, 3...)')),
                ('isi', models.TextField()),
                ('kategori', models.CharField(choices=[('bulat', 'Bilangan Bulat'), ('desimal', 'Bilangan Desimal')], max_length=50)),
            ],
            options={
                'ordering': ['urutan'],
            },
        ),
        migrations.CreateModel(
            name='ProgresMateri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selesai', models.BooleanField(default=False)),
                ('tanggal_selesai', models.DateTimeField(auto_now_add=True)),
                ('materi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.materi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'materi')},
            },
        ),
    ]
