# Generated by Django 5.2.7 on 2025-12-18 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_materi_progresmateri'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materi',
            name='isi',
        ),
        migrations.RemoveField(
            model_name='progresmateri',
            name='tanggal_selesai',
        ),
        migrations.AddField(
            model_name='materi',
            name='file_template',
            field=models.CharField(default='', help_text='Path ke file HTML di folder templates', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='materi',
            name='urutan',
            field=models.IntegerField(),
        ),
    ]
