# Generated by Django 5.2.7 on 2025-11-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_profile_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='foto',
            field=models.ImageField(default='profile_pics/default.jpg', upload_to='profile_pics'),
        ),
    ]
