# Generated by Django 5.2.7 on 2025-11-21 01:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_feedback_nilai'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kuis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('kategori_materi', models.CharField(max_length=50)),
                ('minimal_nilai', models.IntegerField(default=60)),
            ],
        ),
        migrations.CreateModel(
            name='ButirSoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teks_soal', models.TextField()),
                ('opsi_a', models.CharField(max_length=200)),
                ('opsi_b', models.CharField(max_length=200)),
                ('opsi_c', models.CharField(max_length=200)),
                ('opsi_d', models.CharField(max_length=200)),
                ('kunci', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], max_length=1)),
                ('kuis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soal_soal', to='main.kuis')),
            ],
        ),
        migrations.CreateModel(
            name='StatusMateri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materi_bulat_selesai', models.BooleanField(default=False)),
                ('materi_desimal_selesai', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
